# Generated by Django 5.2.8 on 2025-12-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('IN', 'Pemasukan (Modal/Omzet)'), ('OUT', 'Pengeluaran (Belanja)')], default='OUT', max_length=3),
        ),
    ]
